DROP TABLE IF EXISTS todos CASCADE;

CREATE TABLE todos (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  date_created DATE NOT NULL,
  date_due DATE NOT NULL,
  priority SMALLINT NOT NULL,
  completed BOOLEAN NOT NULL
);
